Mobile menu
HatimDev-HE/Portfolio-site-4 pull request #6
Opened 2022-06-20 13:40 UTC by HatimDev-HE

Added mobile menu and redirection to particular section when click on the nav-links

2022-06-20 15:00 UTC, vechicin requested changes
# Hi @HatimDev-HE ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good first attempt at implementing the mobile menu

## Required Changes ♻️

- [ ] You need to set up ESLint, the linters for JavaScript, please do so.

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-20 15:00 UTC, vechicin commented on styles.css
> +}
I cannot see the `X` close button.

<img width="186" alt="Screen Shot 2022-06-20 at 9 51 27" src="https://user-images.githubusercontent.com/82426682/174628539-e64f3a9e-76a2-47e0-888f-aa360400bfc0.png">

Please add it.

Additionally, your design doesn't follow the template design.

<img width="159" alt="Screen Shot 2022-06-20 at 9 54 42" src="https://user-images.githubusercontent.com/82426682/174629221-f090ba61-f37f-4868-97e3-889e624915f3.png">

Please fix it.

<img width="841" alt="Screen Shot 2022-06-20 at 9 56 22" src="https://user-images.githubusercontent.com/82426682/174629533-79bd17da-f58d-40e3-998c-ef74bf5e5216.png">

2022-06-20 15:01 UTC, vechicin commented
https://github.com/HatimDev-HE/Portfolio-site-4/blob/61c6390e881fc9ccbdb41ce860c795fe7159b036/styles.css#L144-L154

I'm not sure what happened, but your desktop design is completely thrown out of whack. I am using Google Chrome, for reference.

<img width="548" alt="Screen Shot 2022-06-20 at 10 01 09" src="https://user-images.githubusercontent.com/82426682/174630419-8e3ad744-ede8-46af-b898-e9de39a85038.png">

Please fix it.

2022-06-20 19:09 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @HatimDev-HE , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-20 19:09 UTC, leonardodiasb commented on styles.css
> +}
- [ ] Your "X" button is partially visible. Looks like the menu-mobile is overlapping it. You could kindly set a higher z-index for the `.hamburger` class over the menu mobile z-index.
- [OPTIONAL] Your hamburger button is almost being cut out of the screen. Kindly review the margin-right of that button.
![image](https://user-images.githubusercontent.com/61919617/174664909-8c63e7ba-bd3e-4d33-8d6f-c55e12301077.png)

2022-06-21 07:42 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @HatimDev-HE ,  

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- menu works well
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-21 07:51 UTC, merged